---
- name: Set role defaults
  set_fact:
    kubernetes: "{{ role_defaults | combine(kubernetes, recursive=True) }}"

- name: Add Grafana Helm repo
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    context: "{{ kubernetes.context }}"
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
  delegate_to: 127.0.0.1

- name: Install alloy deployment
  when: kubernetes.alloy.deployment.enabled
  block:
    - name: Install alloy-config-controller
      when: kubernetes.alloy.config_controller.enabled
      block:
        - name: Template alloy config controller kustomization
          template:
            src: deployment-acc-kustomization.yaml.j2
            dest: "{{ haondt.artifacts }}/kustomization.yaml"
          delegate_to: 127.0.0.1

        - name: Build acc with kustomize
          shell: kubectl kustomize "{{ haondt.artifacts }}" --load-restrictor LoadRestrictionsNone
          register: acc_manifests
          delegate_to: 127.0.0.1
          vars:
            ansible_python_interpreter: "{{ ansible_playbook_python }}"

        - name: Apply acc manifests
          k8s:
            kubeconfig: "{{ kubernetes.kubeconfig }}"
            state: present
            definition: "{{ acc_manifests.stdout | from_yaml_all }}"
            context: "{{ kubernetes.context }}"
          delegate_to: 127.0.0.1

        - name: Template acc custom resources
          template:
            src: deployment-acc-custom-resources.yaml.j2
            dest: "{{ haondt.artifacts }}/deployment-acc-custom-resources.yaml"
          delegate_to: 127.0.0.1

        - name: Apply acc custom resources
          k8s:
            kubeconfig: "{{ kubernetes.kubeconfig }}"
            context: "{{ kubernetes.context }}"
            state: present
            src: "{{ haondt.artifacts }}/deployment-acc-custom-resources.yaml"
          delegate_to: 127.0.0.1

    - name: Install alloy via helm
      when: kubernetes.alloy.config_controller.enabled
      delegate_to: 127.0.0.1
      block:
        - name: Template Alloy helm values
          template:
            src: deployment-alloy-helm-values.yaml.j2
            dest: "{{ haondt.artifacts }}/deployment-alloy-helm-values.yaml"
        - name: Install Alloy Helm chart
          kubernetes.core.helm:
            kubeconfig: "{{ kubernetes.kubeconfig }}"
            context: "{{ kubernetes.context }}"
            name: alloy
            chart_ref: grafana/alloy
            release_namespace: "{{ kubernetes.alloy.deployment.namespace }}"
            chart_version: "{{ kubernetes.alloy.version }}"
            release_state: present
            create_namespace: true
            values_files:
              - "{{ haondt.artifacts }}/deployment-alloy-helm-values.yaml"

- name: Install alloy daemonset
  when: kubernetes.alloy.daemonset.enabled
  block:
    - name: Install alloy-config-controller
      when: kubernetes.alloy.config_controller.enabled
      block:
        - name: Template alloy config controller kustomization
          template:
            src: daemonset-acc-kustomization.yaml.j2
            dest: "{{ haondt.artifacts }}/kustomization.yaml"
          delegate_to: 127.0.0.1

        - name: Build acc with kustomize
          shell: kubectl kustomize "{{ haondt.artifacts }}" --load-restrictor LoadRestrictionsNone
          register: acc_manifests
          delegate_to: 127.0.0.1
          vars:
            ansible_python_interpreter: "{{ ansible_playbook_python }}"

        - name: Apply acc manifests
          k8s:
            kubeconfig: "{{ kubernetes.kubeconfig }}"
            state: present
            definition: "{{ acc_manifests.stdout | from_yaml_all }}"
            context: "{{ kubernetes.context }}"
          delegate_to: 127.0.0.1

        - name: Template acc custom resources
          template:
            src: daemonset-acc-custom-resources.yaml.j2
            dest: "{{ haondt.artifacts }}/daemonset-acc-custom-resources.yaml"
          delegate_to: 127.0.0.1

        - name: Apply acc custom resources
          k8s:
            kubeconfig: "{{ kubernetes.kubeconfig }}"
            context: "{{ kubernetes.context }}"
            state: present
            src: "{{ haondt.artifacts }}/daemonset-acc-custom-resources.yaml"
          delegate_to: 127.0.0.1

    - name: Install alloy via helm
      when: kubernetes.alloy.config_controller.enabled
      delegate_to: 127.0.0.1
      block:
        - name: Template Alloy helm values
          template:
            src: daemonset-alloy-helm-values.yaml.j2
            dest: "{{ haondt.artifacts }}/daemonset-alloy-helm-values.yaml"
        - name: Install Alloy Helm chart
          kubernetes.core.helm:
            kubeconfig: "{{ kubernetes.kubeconfig }}"
            context: "{{ kubernetes.context }}"
            name: alloy
            chart_ref: grafana/alloy
            release_namespace: "{{ kubernetes.alloy.daemonset.namespace }}"
            chart_version: "{{ kubernetes.alloy.version }}"
            release_state: present
            create_namespace: true
            values_files:
              - "{{ haondt.artifacts }}/daemonset-alloy-helm-values.yaml"
