enabled: true
load_balancer_ip: "192.168.1.110"
version: v2.1.2
crds:
  version: v2.1.2

listeners:
  haondt-dev:
    hostname: '*.haondt.dev'
  marble-local-haondt-dev:
    hostname: '*.marble.local.haondt.dev'
  marble-kg-local-haondt-dev:
    hostname: '*.marble-kg.local.haondt.dev'

