include:
  - project: 'haondt/CICD/pipelines'
    ref: main
    file: 'generate.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == "web"
  - local: trigger.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger"

