stages:
  - bootstrap
  - scheduled

include:
  - project: 'haondt/CICD/pipelines'
    ref: main
    file: 'generate.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == "web"
scheduled:
  stage: scheduled
  environment: scheduled
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
  script:
    - echo "test"

