include:
  - project: 'haondt/CICD/pipelines'
    ref: main
    file: 'generate.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - base

scheduled:
  stage: base
  environment: scheduled
  rules:
    - if: $CI_PIPELINES_SOURCE == "schedule"
  script:
    - echo "test"

