variables:
  PIPELINE_NAME: '$CI_COMMIT_MESSAGE'

default:
  artifacts:
    expire_in: 1 day

stages:
  - base

workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"

a-deb-update:
  stage: base
  environment: trigger
  image: registry.gitlab.com/haondt/cicd/registry/infrastructure-runner:ansible-refactor-efa5d9e6
  rules:
    - if: $PLAYBOOK == "a-deb-update"
  script:
    - cp $SECRETS deployment/secrets.yml
    - cd deployment && make a-deb-update TARGET=$TARGET
