---
k3s_server_location: "/var/lib/rancher/k3s"
k3s_version: "{{ k3s_version | default('v1.28.8+k3s1') }}"
k3s_extra_server_args: ""
k3s_systemd_dir: "/etc/systemd/system"
k3s_kubeconfig: ~/.kube/config.new
k3s_cluster_context: "{{ target_hosts }}"
k3s_use_external_database: false
k3s_user_kubectl: true

k3s_api_endpoint: "{{ hostvars[groups[target_hosts][0]]['ansible_host'] | default(groups[target_hosts][0]) }}"
k3s_api_port: 6443


