enabled: true
deployment:
  enabled: true
  base_config: |
    [[ kubernetes.alloy.prometheus_receiver | indent(4) ]]
    [[ kubernetes.alloy.loki_receiver | indent(4) ]]

    [[ kubernetes.alloy.blackbox.scrape | indent(4) ]]
    [[ kubernetes.alloy.kube_state_metrics.scrape | indent(4) ]]
  partial_components:
    [[kubernetes.alloy.blackbox.partial_components | to_yaml | indent(4)]]
daemonset:
  enabled: true
  node_exporter:
    enabled: true
    mounts:
      celery: /mnt/celery
      pepper: /mnt/pepper
      rhyolite: /mnt/rhyolite/gabbro
  base_config: |
    [[ kubernetes.alloy.prometheus_receiver | indent(4) ]]
    [[ kubernetes.alloy.loki_receiver | indent(4) ]]

    [[ kubernetes.alloy.node_metrics | indent(4) ]]
    [[ kubernetes.alloy.pod_logs | indent(4) ]]

    // dgcm-exporter
    discovery.kubernetes "dcgm_exporter" {
      role = "pod"
      selectors {
        role = "pod"
        field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname) + ",metadata.namespace=dcgm-exporter"
        label = "app.kubernetes.io/component=dcgm-exporter,app.kubernetes.io/instance=dcgm-exporter,app.kubernetes.io/name=dcgm-exporter"
      }
    }
    prometheus.scrape "dcgm_exporter" {
      targets = discovery.kubernetes.dcgm_exporter.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    [[ kubernetes.alloy.smartctl.scrape | indent(4) ]]

config_controller:
  enabled: true
  version: alloy-config-controller/v0.0.3
  # controller_image: registry.gitlab.com/haondt/cicd/registry/alloy-config-controller:main-bb237a6a
version: v1.2.1
