---
- name: Set role defaults
  set_fact:
    kubernetes: "{{ role_defaults | combine(kubernetes, recursive=True) }}"

- name: Template ingress-nginx kustomization
  template:
    src: kustomization.yaml.j2
    dest: "{{ haondt.artifacts }}/kustomization.yaml"
  delegate_to: 127.0.0.1

- name: Install ingress-nginx via Helm
  block:
    - name: Template ingress-nginx helm values
      template:
        src: ingress-nginx-helm-values.yaml.j2
        dest: "{{ haondt.artifacts }}/ingress-nginx-helm-values.yaml"
      delegate_to: 127.0.0.1
    - name: Install ingress-nginx Helm chart
      kubernetes.core.helm:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        context: "{{ kubernetes.context }}"
        name: ingress-nginx
        chart_ref: ingress-nginx
        chart_repo_url: https://kubernetes.github.io/ingress-nginx
        namespace: "{{ kubernetes.ingress_nginx.namespace }}"
        chart_version: "{{ kubernetes.ingress_nginx.version }}"
        release_state: present
        create_namespace: true
        values_files:
          - "{{ haondt.artifacts }}/ingress-nginx-helm-values.yaml"
  delegate_to: 127.0.0.1

- name: Wait for ingress-nginx controller to be ready
  k8s_info:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    context: "{{ kubernetes.context }}"
    api_version: apps/v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300
  delegate_to: 127.0.0.1

- name: Get ingress-nginx service ports
  k8s_info:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    context: "{{ kubernetes.context }}"
    api_version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
  register: ingress_service
  delegate_to: 127.0.0.1


- block:
  - name: Template ingress-nginx Calico custom resources
    template:
      src: calico-resources.yaml.j2
      dest: "{{ haondt.artifacts }}/ingress-nginx-calico-resources.yaml"
    delegate_to: 127.0.0.1

  - name: Apply ingress-nginx Calico custom resources
    k8s:
      kubeconfig: "{{ kubernetes.kubeconfig }}"
      context: "{{ kubernetes.context }}"
      state: present
      src: "{{ haondt.artifacts }}/ingress-nginx-calico-resources.yaml"
    delegate_to: 127.0.0.1
  when: kubernetes.calico.enabled
