---
- name: Set role defaults
  set_fact:
    kubernetes: "{{ role_defaults | combine(kubernetes, recursive=True) }}"

- name: Template rathole kustomization
  template:
    src: kustomization.yaml.j2
    dest: "{{ haondt.artifacts }}/kustomization.yaml"
  delegate_to: 127.0.0.1

- name: Build rathole manifests with kustomize
  shell: kubectl kustomize "{{ haondt.artifacts }}" --load-restrictor LoadRestrictionsNone
  register: rathole_manifests
  delegate_to: 127.0.0.1
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- name: Apply rathole manifests
  k8s:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    state: present
    definition: "{{ rathole_manifests.stdout | from_yaml_all }}"
    context: "{{ kubernetes.context }}"
  delegate_to: 127.0.0.1


- name: Template rathole custom resources
  template:
    src: custom-resources.yaml.j2
    dest: "{{ haondt.artifacts }}/rathole-custom-resources.yaml"
  delegate_to: 127.0.0.1

- name: Apply rathole custom resources
  k8s:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    context: "{{ kubernetes.context }}"
    state: present
    src: "{{ haondt.artifacts }}/rathole-custom-resources.yaml"
  delegate_to: 127.0.0.1

