---
- name: Set role defaults
  set_fact:
    kubernetes: "{{ role_defaults | combine(kubernetes, recursive=True) }}"

- name: Install kube-state-metrics via helm
  block:
    - name: Add Prometheus community Helm repo
      kubernetes.core.helm_repository:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        context: "{{ kubernetes.context }}"
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
    - name: Install kube-state-metrics Helm chart
      kubernetes.core.helm:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        context: "{{ kubernetes.context }}"
        name: kube-state-metrics
        chart_ref: prometheus-community/kube-state-metrics
        release_namespace: "kube-state-metrics"
        chart_version: "{{ kubernetes.kube_state_metrics.version }}"
        release_state: present
        create_namespace: true
        values:
          metricLabelsAllowlist:
            - jobs=[deployment.haondt.dev/name,deployment.haondt.dev/part-of,deployment.haondt.dev/project]
            - pods=[deployment.haondt.dev/name,deployment.haondt.dev/part-of,deployment.haondt.dev/project]

  delegate_to: 127.0.0.1
- name: Install alloy communication resources
  delegate_to: 127.0.0.1
  block:
    - name: Template alloy custom resources
      template:
        src: alloy-resources.yaml.j2
        dest: "{{ haondt.artifacts }}/kube-state-metrics-alloy-resources.yaml"
    - name: Apply alloy custom resources
      k8s:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        context: "{{ kubernetes.context }}"
        state: present
        src: "{{ haondt.artifacts }}/kube-state-metrics-alloy-resources.yaml"
