---
- name: Create service account namespaces
  k8s:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.value.namespace | default(kubernetes.default_namespace) }}"
  loop: "{{ kubernetes.service_accounts | dict2items }}"

