---
role_defaults:
  alloy:
    daemonset:
      enabled: false
      node_exporter:
        enabled: false
        mounts: {}
      partial_components: {}
      base_config: ''
    deployment:
      enabled: false
      partial_components: {}
      base_config: ''
    version: v1.2.1
    config_controller:
      enabled: false
      daemonset:
        namespace: alloy-daemonset-config-controller
      deployment:
        namespace: alloy-deployment-config-controller
      version: alloy-config-controller/v0.0.2
