---
- name: Set role defaults
  set_fact:
    kubernetes: "{{ role_defaults | combine(kubernetes, recursive=True) }}"

- name: Install argo-workflows via helm
  when: kubernetes.argo.workflows.enabled
  block:
    - name: Add argo Helm repo
      kubernetes.core.helm_repository:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        context: "{{ kubernetes.context }}"
        name: argo
        repo_url: https://argoproj.github.io/argo-helm
    - name: Install argo-workflows Helm chart
      kubernetes.core.helm:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        context: "{{ kubernetes.context }}"
        name: argo-workflows
        chart_ref: argo/argo-workflows
        release_namespace: "argo-workflows"
        chart_version: "{{ kubernetes.argo.workflows.version }}"
        release_state: present
        create_namespace: true
        # values: {}
  delegate_to: 127.0.0.1
