config_file: flint.conf
local_zones:
  flint: &flint_ip 192.168.1.132
  flint.local.haondt.dev: *flint_ip

  rhyolite: &rhyolite_ip 192.168.1.88
  rhyolite.local.haondt.dev: *rhyolite_ip

  gabbro: 192.168.1.78
  gabbro.local.haondt.dev: 192.168.1.215

  aurora: 192.168.1.116

  basalt: 192.168.1.139
  basalt.local.haondt.dev: 192.168.1.205

  # control plane ip is 192.168.1.100, ingress is on 192.168.1.101
  marble.local.haondt.dev: 192.168.1.101
  marble-kg.local.haondt.dev: 192.168.1.110
