---
- name: Add Python deps
  hosts: "{{ target_hosts }}"
  roles:
    - role: kubernetes/python-kubernetes

- name: Configure Kubernetes cluster
  hosts: "{{ target_hosts }}"
  run_once: true
  roles:
    - role: kubernetes/install-calico
      when: kubernetes.install_calico | default(false)
    - role: kubernetes/configure-namespaces
    - role: kubernetes/configure-service-accounts
    - role: kubernetes/configure-cluster-role-bindings
    - role: kubernetes/configure-service-account-tokens
