---
- name: Add Python deps
  hosts: "{{ target_hosts }}"
  roles:
    - role: kubernetes/python-kubernetes

- name: Configure Kubernetes cluster
  hosts: "{{ target_hosts }}"
  run_once: true
  roles:
    - role: kubernetes/install-calico
      when: kubernetes.calico.enabled
    - role: kubernetes/install-kube-vip-cloud-controller
      when: kubernetes.kube_vip_cloud_controller.enabled
    - role: kubernetes/install-ingress-nginx
      when: kubernetes.ingress_nginx.enabled
    - role: kubernetes/install-metallb
      when: kubernetes.metallb.enabled
    - role: kubernetes/install-cert-manager
      when: kubernetes.cert_manager.enabled
    - role: kubernetes/install-rathole
      when: kubernetes.rathole.enabled
    - role: kubernetes/install-alloy
      when: kubernetes.alloy.enabled
    - role: kubernetes/install-charon
      when: kubernetes.charon.enabled
    - role: kubernetes/install-gitlab-runner
      when: kubernetes.gitlab_runner.enabled

- name: Configure kubernetes cluster (per-host)
  hosts: "{{ target_hosts }}"
  roles:
    - role: kubernetes/install-longhorn
      when: kubernetes.longhorn.enabled
    - role: kubernetes/install-nvidia-devices
      when: nvidia is defined and nvidia.enabled

- name: Configure remaining items
  hosts: "{{ target_hosts }}"
  run_once: true
  roles:
    - role: kubernetes/configure-namespaces
    - role: kubernetes/configure-service-accounts
    - role: kubernetes/configure-cluster-role-bindings
    - role: kubernetes/configure-service-account-tokens
