---
- name: Set role defaults
  set_fact:
    kubernetes: "{{ role_defaults | combine(kubernetes, recursive=True) }}"

- name: Template Calico kustomization
  template:
    src: kustomization.yaml.j2
    dest: "{{ haondt.artifacts }}/kustomization.yaml"
  delegate_to: 127.0.0.1

- name: Build Calico manifests with kustomize
  shell: kubectl kustomize "{{ haondt.artifacts }}" --load-restrictor LoadRestrictionsNone
  register: calico_manifests
  delegate_to: 127.0.0.1
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- name: Apply Calico manifests
  k8s:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    state: present
    definition: "{{ calico_manifests.stdout | from_yaml_all }}"
  delegate_to: 127.0.0.1

- name: Wait for Tigera Operator to be ready
  k8s_info:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    name: tigera-operator
    namespace: tigera-operator
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300

- name: Template Calico custom resources
  template:
    src: custom-resources.yaml.j2
    dest: "{{ haondt.artifacts }}/calico-custom-resources.yaml"
  delegate_to: 127.0.0.1

- name: Apply Calico custom resources
  k8s:
    kubeconfig: "{{ kubernetes.kubeconfig }}"
    state: present
    src: "{{ haondt.artifacts }}/calico-custom-resources.yaml"
  delegate_to: 127.0.0.1
