gabbro:
  ansible_host: [[ kubernetes.cluster_ip ]]
  nvidia:
    enabled: true
  storage:
    - by_path: /dev/disk/by-path/pci-0000:03:00.0-sas-phy0-lun-0
      mount: /mnt/carrot-1
    - by_path: /dev/disk/by-path/pci-0000:03:00.0-sas-phy2-lun-0
      mount: /mnt/carrot-2
    - by_path: /dev/disk/by-path/pci-0000:03:00.0-sas-phy3-lun-0
      mount: /mnt/carrot-3
